### ISSUE TITLE
BIZZARE AND ILLEGAL!

### ISSUE THREAD

**Issue by ombhatt2** [RidwanA123/Crazy-Error#2]
this is not good, I would advise you to take this off github, it is illegal, If you dont you will be reported

**Comment by ombhatt2** [comment]
If you want freevbucks you need to buy, its like saying we can get everything for free, no its not like that, please refrain from doing so and if it causes BSOD its even worse Take it off!

**Comment by RidwanA123** [comment]
> this is not good, I would advise you to take this off github, it is illegal, If you dont you will be reported

Ight.

**Comment by ombhatt2** [comment]
Thank you please take it off

**Comment by RidwanA123** [comment]
> Thank you please take it off

![image](https://user-images.githubusercontent.com/58993858/109349490-0744f100-7844-11eb-9cbf-9beaf7017419.png)

**Comment by ombhatt2** [comment]
Stop please take it off!

**Comment by ombhatt2** [comment]
It is only for your own good, if you cant post anything good, then simply dont :)

**Comment by ombhatt2** [comment]
See  https://docs.github.com/articles/github-community-guidelines Its illegal to post these things.

**Comment by RidwanA123** [comment]
> See https://docs.github.com/articles/github-community-guidelines Its illegal to post these things.

This isn't even malware.

**Comment by n5q** [comment]
> See https://docs.github.com/articles/github-community-guidelines Its illegal to post these things.

![image](https://user-images.githubusercontent.com/43859271/109349859-95b97280-7844-11eb-8606-94d49aed7f68.png)
It says right here, hosting malware samples for analysis and research is not prohibited on GitHub as long as you are not actively using them for malicious purposes. 

> "The publication and distribution of such source code has educational value and provides a net benefit to the security community."

**Comment by RidwanA123** [comment]
> > See https://docs.github.com/articles/github-community-guidelines Its illegal to post these things.
> 
> ![image](https://user-images.githubusercontent.com/43859271/109349859-95b97280-7844-11eb-8606-94d49aed7f68.png)
> It says right here, hosting malware samples for analysis and research is not prohibited on GitHub as long as you are not actively using them for malicious purposes.

Which I'm not for malicious purposes...

**Comment by ombhatt2** [comment]
But this is not benefiting the community it is illegal

**Comment by ombhatt2** [comment]
There is no point of paying for vbucks then, the companies dont make any profit

**Comment by ombhatt2** [comment]
It dosent matter its illegal

**Comment by Luke-zhang-04** [comment]
Please stop Harassing Ridwan please and thank you!

**Comment by ombhatt2** [comment]
It is not harrassing, It Is a issue which is serious

**Comment by ombhatt2** [comment]
If you want to post, there is no harm in posting other things which are better, just dont post illegal things

**Comment by RidwanA123** [comment]
> It dosent matter its illegal

Ok child

**Comment by ombhatt2** [comment]
Can you not be offensive please?

**Comment by n5q** [comment]
> But this is not benefiting the community it is illegal

It is not illegal to distribute malware samples, analyzing and understanding how malware operates is valuable knowledge when dealing with cybersecurity. GitHub makes it clear in their terms of service that hosting malware samples is beneficial to the security community. It is illegal to use the samples for nefarious purposes but simply displaying them to the public as this repository is doing is perfectly legal. 
I recommend that you read this README. https://github.com/ytisf/theZoo

**Comment by ombhatt2** [comment]
But you are not allowed to post something that is illegal, you cannot post a code of FreeVbucks. 
![Uploading image.png…]()

**Comment by ombhatt2** [comment]
Anyways I had to say what I had to

**Comment by ombhatt2** [comment]
And Ridwan (owner) saying " ok child" is also offensive and does not comply with the github community guidelines, so If I were you can post something else and your done!

**Comment by n5q** [comment]
> But you are not allowed to post something that is illegal, you cannot post a code of FreeVbucks.
> Uploading image.png…

Did you read what I said? Hosting malware samples is NOT illegal, it only becomes illegal when you actually hit the run button with malicious intent. Can you cite a law to back up your claims?

**Comment by RidwanA123** [comment]
> And Ridwan (owner) saying " ok child" is also offensive and does not comply with the github community guidelines, so If I were you can post something else and your done!

Just a quick question, what are you trying to accomplish?

**Comment by ombhatt2** [comment]
> > But you are not allowed to post something that is illegal, you cannot post a code of FreeVbucks.
> > Uploading image.png…
> 
> Did you read what I said? Hosting malware samples is NOT illegal, it only becomes illegal when you actually hit the run button with malicious intent. Can you cite a law to back up your claims?

There is no need for that, it is simple, you are not allowed to post illegal content, FreeVbucks is not acceptable, its getting freevbucks in a wrong way, its called stealing.

**Comment by ombhatt2** [comment]
> > And Ridwan (owner) saying " ok child" is also offensive and does not comply with the github community guidelines, so If I were you can post something else and your done!
> 
> Just a quick question, what are you trying to accomplish?

I am trying to save you from the consequences

**Comment by n5q** [comment]
> > > But you are not allowed to post something that is illegal, you cannot post a code of FreeVbucks.
> > > Uploading image.png…
> > 
> > 
> > Did you read what I said? Hosting malware samples is NOT illegal, it only becomes illegal when you actually hit the run button with malicious intent. Can you cite a law to back up your claims?
> 
> There is no need for that, it is simple, you are not allowed to post illegal content, FreeVbucks is not acceptable, its getting freevbucks in a wrong way, its called stealing.

It becomes wrong when you actually hit the run button and execute the code, the point of malware samples is to analyze how they operate to better understand how to secure your own programs so that they are not vulnerable to the same attack vectors that the malware takes advantage of. Studying malware is NOT illegal and is a common cybersecurity practice. I am asking you again to cite a law that states otherwise.

**Comment by ombhatt2** [comment]
Its called piracy, its not a good thing

**Comment by n5q** [comment]
> > > And Ridwan (owner) saying " ok child" is also offensive and does not comply with the github community guidelines, so If I were you can post something else and your done!
> > 
> > 
> > Just a quick question, what are you trying to accomplish?
> 
> I am trying to save you from the consequences

There are large archives of active malware samples (one of which I linked here earlier) all over GitHub with tens of thousands of stars. If hosting samples was such a serious issue then why have these repositories not been taken down for a violation of GitHub terms or United States law and why have the repository owners not faces any legal consequences
https://github.com/search?o=desc&q=malware&s=stars&type=Repositories

**Comment by n5q** [comment]
> Its called piracy, its not a good thing

Again, it is only wrong **when you hit the run button**, hosting malware samples is not the same. https://www.cybercom.mil/Media/News/News-Display/Article/1681533/new-cnmf-initiative-shares-malware-samples-with-cybersecurity-industry/ This is the United States Department of Defense, they post regular samples of active malware for public research. These samples can be used for malicious purposes which would then be illegal, but the act of making them public is not.

**Comment by ombhatt2** [comment]
Again sir, What the point I want to come to again and again is that this is piracy, and by posting this code (freevbucks) it is illegal to do so since it can get people banned from the game (Fortnite) and it is an illegal act to do. And if it gets reported, then you may face consequences or removal from GitHub. Coming to the point, I suggest you view the laws of Canada for File sharing: https://en.wikipedia.org/wiki/File_sharing_in_Canada

**Comment by RidwanA123** [comment]
> Its called piracy, its not a good thing

I made this myself, stop making things up in your head.

**Comment by RidwanA123** [comment]
> Again sir, What the point I want to come to again and again is that this is piracy, and by posting this code (freevbucks) it is illegal to do so since it can get people banned from the game (Fortnite) and it is an illegal act to do. And if it gets reported, then you may face consequences or removal from GitHub. Coming to the point, I suggest you view the laws of Canada for File sharing: https://en.wikipedia.org/wiki/File_sharing_in_Canada

But aren't you POTUS in discord and calling yourself Trump? So you are living in the US and not in Canada based on your logic.

**Comment by ombhatt2** [comment]
> > Again sir, What the point I want to come to again and again is that this is piracy, and by posting this code (freevbucks) it is illegal to do so since it can get people banned from the game (Fortnite) and it is an illegal act to do. And if it gets reported, then you may face consequences or removal from GitHub. Coming to the point, I suggest you view the laws of Canada for File sharing: https://en.wikipedia.org/wiki/File_sharing_in_Canada
> 
> But aren't you POTUS in discord and calling yourself Trump? So you are living in the US and not in Canada based on your logic.

Excuse me, I do not get what you are saying?

**Comment by ombhatt2** [comment]
> > Its called piracy, its not a good thing
> 
> I made this myself, stop making things up in your head.

I did not say this is copied code, I said this is legit piracy.

**Comment by RidwanA123** [comment]
> > > Its called piracy, its not a good thing
> > 
> > 
> > I made this myself, stop making things up in your head.
> 
> I did not say this is copied code, I said this is legit piracy.

Also Om, the freevbucks!.bat is the trigger to run the program, check readme.

**Comment by RidwanA123** [comment]
> > > Its called piracy, its not a good thing
> > 
> > 
> > I made this myself, stop making things up in your head.
> 
> I did not say this is copied code, I said this is legit piracy.

Define piracy.

**Comment by n5q** [comment]
> Again sir, What the point I want to come to again and again is that this is piracy, and by posting this code (freevbucks) it is illegal to do so since it can get people banned from the game (Fortnite) and it is an illegal act to do. And if it gets reported, then you may face consequences or removal from GitHub. Coming to the point, I suggest you view the laws of Canada for File sharing: https://en.wikipedia.org/wiki/File_sharing_in_Canada

This is not copyrighted material, the law that you are referring to references direct downloads of copyrighted content (eg, movies, game files), NOT malware samples. There is no content being hosted here that is intellectual property of Epic Games therefore that law does not apply.

**Comment by n5q** [comment]
> > > > And Ridwan (owner) saying " ok child" is also offensive and does not comply with the github community guidelines, so If I were you can post something else and your done!
> > > 
> > > 
> > > Just a quick question, what are you trying to accomplish?
> > 
> > 
> > I am trying to save you from the consequences
> 
> There are large archives of active malware samples (one of which I linked here earlier) all over GitHub with tens of thousands of stars. If hosting samples was such a serious issue then why have these repositories not been taken down for a violation of GitHub terms or United States law and why have the repository owners not faces any legal consequences
> https://github.com/search?o=desc&q=malware&s=stars&type=Repositories



> > Its called piracy, its not a good thing
> 
> Again, it is only wrong **when you hit the run button**, hosting malware samples is not the same. https://www.cybercom.mil/Media/News/News-Display/Article/1681533/new-cnmf-initiative-shares-malware-samples-with-cybersecurity-industry/ This is the United States Department of Defense, they post regular samples of active malware for public research. These samples can be used for malicious purposes which would then be illegal, but the act of making them public is not.

@Omcodez1503

**Comment by RidwanA123** [comment]
> > > Its called piracy, its not a good thing
> > 
> > 
> > I made this myself, stop making things up in your head.
> 
> I did not say this is copied code, I said this is legit piracy.

Who do you think you are Om? The NSA.

freevbucks.bat does NOT give you vbucks, its a joke/meme from 2018. It even says that in the readme.

**Comment by Sartorra** [comment]
> this is not good, I would advise you to take this off github, it is illegal, If you dont you will be reported

This is not against the TOS of github. Please stop trying to be a rule enforcer if you think it is breaking the rules just report it to github simple.
