### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by ombhatt2** [RidwanA123/Crazy-Error#4]
Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start! - This is not acceptable as well, It says it will cause BSOD, which is bad for users who want to try they will end up breaking their computer, what do you think, dont you think this is bad?

**Comment by ombhatt2** [comment]
This code: md C:\freeram

xcopy "KirbyError_Source" "C:\freeram" /E
cd KirbyError_Source
### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?

**Comment by RidwanA123** [comment]
> Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start! - This is not acceptable as well, It says it will cause BSOD, which is bad for users who want to try they will end up breaking their computer, what do you think, dont you think this is bad?

The BSOD won't even damage the computer. What are you smoking.

**Comment by n5q** [comment]
> This code: md C:\freeram
> 
> xcopy "KirbyError_Source" "C:\freeram" /E
> cd KirbyError_Source
> ### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?

I assume you have read my messages in the other issue? The answer to your problem is there

**Comment by ombhatt2** [comment]
> > Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start! - This is not acceptable as well, It says it will cause BSOD, which is bad for users who want to try they will end up breaking their computer, what do you think, dont you think this is bad?
> 
> The BSOD won't even damage the computer. What are you smoking.

Do you know what meaning there can be for damage " one is physical damage, and other is temporary damage to the system (not physcial). With BSOD, all of one's file will be deleted once they go in the process of recovering?

**Comment by ombhatt2** [comment]
> > This code: md C:\freeram
> > xcopy "KirbyError_Source" "C:\freeram" /E
> > cd KirbyError_Source
> > ### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?
> 
> I assume you have read my messages in the other issue? The answer to your problem is there

I am no one to tell you to implement things, but going forward this will be bad for your future reputation.

**Comment by RidwanA123** [comment]
> > This code: md C:\freeram
> > xcopy "KirbyError_Source" "C:\freeram" /E
> > cd KirbyError_Source
> > ### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?
> 
> I assume you have read my messages in the other issue? The answer to your problem is there

He closed the issue.

**Comment by n5q** [comment]
> > > Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start! - This is not acceptable as well, It says it will cause BSOD, which is bad for users who want to try they will end up breaking their computer, what do you think, dont you think this is bad?
> > 
> > 
> > The BSOD won't even damage the computer. What are you smoking.
> 
> Do you know what meaning there can be for damage " one is physical damage, and other is temporary damage to the system (not physcial). With BSOD, all of one's file will be deleted once they go in the process of recovering?

This is untrue and has not been true for a decade. The whole purpose of a blue screen is to make sure that files are NOT damaged when a system exception occurs. The sample does not touch any of the users files and there would be no reason for the automatic recovery process to touch them

**Comment by n5q** [comment]
> > > This code: md C:\freeram
> > > xcopy "KirbyError_Source" "C:\freeram" /E
> > > cd KirbyError_Source
> > > ### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?
> > 
> > 
> > I assume you have read my messages in the other issue? The answer to your problem is there
> 
> I am no one to tell you to implement things, but going forward this will be bad for your future reputation.

How so?

**Comment by n5q** [comment]
> why post something that causes BSOD?

There are large archives of active malware samples (one of which I linked here earlier) all over GitHub with tens of thousands of stars. If hosting samples was such a serious issue then why have these repositories not been taken down for a violation of GitHub terms or United States law and why have the repository owners not faces any legal consequences
https://github.com/search?o=desc&q=malware&s=stars&type=Repositories

Again, it is only wrong **when you hit the run button**, hosting malware samples is not the same. https://www.cybercom.mil/Media/News/News-Display/Article/1681533/new-cnmf-initiative-shares-malware-samples-with-cybersecurity-industry/ This is the United States Department of Defense, they post regular samples of active malware for public research. These samples can be used for malicious purposes which would then be illegal, but the act of making them public is not.

**Comment by Luke-zhang-04** [comment]
> > > This code: md C:\freeram
> > > xcopy "KirbyError_Source" "C:\freeram" /E
> > > cd KirbyError_Source
> > > ### **start startwbsod.vbs** - This part this not good, it makes BSOD occur on one's computer, even if it dosent, why post something that causes BSOD?
> > 
> > 
> > I assume you have read my messages in the other issue? The answer to your problem is there
> 
> I am no one to tell you to implement things, but going forward this will be bad for your future reputation.

I am no one to tell you to change things, but going forward this will be bad for your future reputation.

**Comment by Luke-zhang-04** [comment]
> Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start! - This is not acceptable as well, It says it will cause BSOD, which is bad for users who want to try they will end up breaking their computer, what do you think, dont you think this is bad?

Read the [REAMDE.md](https://github.com/RidwanA123/Crazy-Error/blob/main/README.md) file jeeeez

> This is a VBS Error Message self made "malware" based on this video: youtube.com/watch?v=lTU-pyQ_anQ&ab_channel=kossi0404
Since it was fake I just gave it a try to make it for real. (WARNING, WILL CAUSE BSOD AFTER THE CYCLE OF ERROR MESSAGES ENDS). Run FreeVBucks!.bat to start!
If you don't want BSOD go into one of the folders and run main.vbs.

**Comment by ombhatt2** [comment]
Its enough, you cant save yourself now

**Comment by n5q** [comment]
> Its enough, you cant save yourself now

is this a threat

**Comment by Luke-zhang-04** [comment]
I feel threatened

**Comment by xxxoxoxoxxx** [comment]
> Its enough, you cant save yourself now

Can't save my self cuz?

SJAM parking lot, monday, square up coward!
I see u hidin behind that monitor. Bald ass freak. U mad as hell!

**Comment by Luke-zhang-04** [comment]
This thing took WAY too long to be closed

**Comment by xxxoxoxoxxx** [comment]
Om
Where u at?
U talkin mad scammer today!

**Comment by xxxoxoxoxxx** [comment]
Om
Where u at?
U talkin some mad scammer today!

**Comment by n5q** [comment]
shut
